README.md, jira/Jira_connector_constants.bal, jira/jira_connector.bal, jira/jira_connector_util_functions.bal, jira/jira_enums.bal, jira/jira_structs.bal
=> Update README.md and refactor code

README.md, jira7/Package.md
=> Add minor changes to Markdown files

README.md, jira7/Package.md
=> Update connector version in markdown files

README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_connector_endpoint.bal, jira7/jira_connector_util_functions.bal, jira7/jira_records.bal
=> Complete Docerina annotations and Add fixes for ballerina v.0.970.0-alpha4 release changes

README.md, jira7/Package.md
=> Update Markdown files

Ballerina.toml, README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_data_mappings.bal, jira7/jira_endpoint.bal, jira7/jira_utils.bal, jira7/tests/README.md
=> Add changes for Ballerina v0.970.0-beta3, Update Markdown files and Add Ballerina.toml

README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_constants.bal, jira7/jira_types.bal, jira7/jira_utils.bal, jira7/tests/README.md
=> Add changes for ballerina v0.970.0-beta10 

.gitignore, Ballerina.toml, jira7/jira_connector.bal
=> Fix a bug for latest build

README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_endpoint.bal, jira7/jira_utils.bal, jira7/tests/README.md, jira7/tests/tests.bal
=> Add compatibility for ballerina v0.970.0-beta14 and minor improvements

README.md, jira7/jira_utils.bal, jira7/tests/README.md
=> Fix for beta15 changes

jira7/Package.md
=> Update to gold standards

Ballerina.toml, jira7/Package.md
=> Extend package overview description

Ballerina.toml, README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_endpoint.bal, jira7/jira_types.bal, jira7/tests/README.md
- Fix syntax issues
- Update markdown files and toml file for 0.980.0 release
=> Prepare connector for Ballerina 0.980.0 release

Ballerina.toml, README.md, jira7/Package.md, jira7/jira_connector.bal, jira7/jira_endpoint.bal, jira7/jira_types.bal, jira7/jira_utils.bal, jira7/tests/README.md
Fix connector with latest ballerina changes.
> Link to the PR for changes to the training content in …
=> Fix connector with latest ballerina changes

.ballerina/.gitignore, .travis.yml, Ballerina.toml, README.md, jira7/Module.md, jira7/jira_connector.bal, jira7/tests/README.md, jira7/tests/tests.bal
Sync with ballerina 0.983.0
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Sync with ballerina 0.983.0

Ballerina.toml, README.md, jira7/Module.md, jira7/jira_endpoint.bal, jira7/tests/README.md
- Fix a bug in remote functions
- Fix markdown and update toml version
=> Release for Ballerina 0.990.0 RC3

Ballerina.toml, jira7/jira_data_mappings.bal, jira7/jira_endpoint.bal, jira7/jira_types.bal, jira7/tests/tests.bal
Fix the test failures of #51 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix the test failure

Ballerina.toml, README.md, jira7/Module.md, jira7/jira_endpoint.bal, jira7/tests/README.md
=> Sync with ballerina 0.990.3

Ballerina.toml, README.md, jira7/Module.md, jira7/jira_utils.bal, jira7/tests/README.md, jira7/tests/tests.bal
Sync with ballerina 0.991.0.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Sync with ballerina 0.991.0

Ballerina.toml, README.md, jira7/Module.md, jira7/jira_constants.bal, jira7/jira_data_mappings.bal, jira7/jira_endpoint.bal, jira7/jira_types.bal, jira7/jira_utils.bal, jira7/tests/tests.bal
Fix for 
https://github.com/wso2-ballerina/module-jira/issues/49
> Link to the PR for changes to the training content in …
=> Remove custom Jira error and use Ballerina error

.travis.yml, Ballerina.lock, Ballerina.toml
Update minor version for release
=> Update minor version for release

README.md, src/jira7/Module.md
=> Fix read-me sample

src/jira7/Module.md
=> Update module.md with sample

src/jira7/jira_endpoint.bal, src/jira7/tests/tests.bal
=> Migrate to ballerina version 1.1.3

.github/workflows/ci.yml, .github/workflows/release.yml, .travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/jira7/Module.md, src/jira7/jira_constants.bal, src/jira7/jira_data_mappings.bal
=> Update connector for ballerina 1.2.0

Ballerina.lock, Ballerina.toml, src/jira/jira_constants.bal, src/jira/jira_data_mappings.bal, src/jira/jira_endpoint.bal, src/jira/jira_types.bal, src/jira/tests/tests.bal
Update the types with the typed defined in the module `ballerinax/jira.commons`. 
> Note: Should be merged after the `ballerinax/jira.commons` is released. 
Depends on: https://github.com/ballerina-platform/module-ballerinax-jira.commons/pull/1
=> Update jira types

.travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/jira/Module.md, src/jira/jira_data_mappings.bal, src/jira/jira_endpoint.bal, src/jira/tests/tests.bal
> $title
Fixes: https://github.com/ballerina-platform/ballerina-lang/issues/24362
=> Migrate connector to ballerina swan lake preview 1
